/*
 * SpriteNameBinder.cs
 * Unity Editor utility for Cocos→Unity migration.
 *
 * Reads .sprite_names.json sidecar files generated by convert_prefab.py
 * and automatically assigns Sprite references to Image components by
 * matching the original Cocos asset file name.
 *
 * Usage:
 *   1. Place this file in Assets/Editor/
 *   2. After importing migrated .prefab/.unity files, run:
 *      Menu → Cocos2Unity → Bind Sprites by Name
 *   3. Or auto-bind on import via the AssetPostprocessor hook.
 *
 * © 2026 cocos-to-unity toolkit
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace Cocos2Unity.Editor
{
    public static class SpriteNameBinder
    {
        // ── Menu Entry ──────────────────────────────────────────
        [MenuItem("Cocos2Unity/Bind Sprites by Name (All Scenes + Prefabs)")]
        public static void BindAllSprites()
        {
            int totalBound = 0;

            // 1. Process all .sprite_names.json files in the project
            string[] jsonGuids = AssetDatabase.FindAssets("t:TextAsset");
            var nameMapFiles = new List<string>();

            // Also search directly for .sprite_names.json files
            string assetsPath = Application.dataPath;
            string[] jsonFiles = Directory.GetFiles(assetsPath, "*.sprite_names.json",
                SearchOption.AllDirectories);

            foreach (string jsonPath in jsonFiles)
            {
                string relativePath = "Assets" + jsonPath.Substring(assetsPath.Length)
                    .Replace('\\', '/');
                nameMapFiles.Add(jsonPath);
                Debug.Log($"[SpriteNameBinder] Found name map: {relativePath}");
            }

            if (nameMapFiles.Count == 0)
            {
                Debug.LogWarning("[SpriteNameBinder] No .sprite_names.json files found. " +
                    "Run convert_prefab.py first.");
                return;
            }

            // 2. Build a global sprite name → Sprite lookup cache
            var spriteCache = BuildSpriteCache();
            Debug.Log($"[SpriteNameBinder] Sprite cache: {spriteCache.Count} entries");

            // 3. Process each name map
            foreach (string jsonPath in nameMapFiles)
            {
                int bound = ProcessNameMap(jsonPath, spriteCache);
                totalBound += bound;
            }

            // 4. Also scan all open scenes for Image components with missing sprites
            totalBound += ScanAndBindOpenScenes(spriteCache);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[SpriteNameBinder] Done! Bound {totalBound} sprite references.");
            EditorUtility.DisplayDialog("Sprite Name Binder",
                $"Bound {totalBound} sprite references by name.", "OK");
        }

        // ── Menu Entry: Selected Only ───────────────────────────
        [MenuItem("Cocos2Unity/Bind Sprites by Name (Selected)")]
        public static void BindSelectedSprites()
        {
            var spriteCache = BuildSpriteCache();
            int totalBound = 0;

            foreach (var obj in Selection.objects)
            {
                string path = AssetDatabase.GetAssetPath(obj);
                if (string.IsNullOrEmpty(path)) continue;

                // Check for sidecar JSON
                string jsonPath = Path.ChangeExtension(path, ".sprite_names.json");
                if (File.Exists(jsonPath))
                {
                    totalBound += ProcessNameMap(jsonPath, spriteCache);
                }

                // If it's a prefab, open and scan
                if (path.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase))
                {
                    totalBound += BindPrefabSprites(path, spriteCache);
                }
            }

            AssetDatabase.SaveAssets();
            Debug.Log($"[SpriteNameBinder] Bound {totalBound} sprites in selection.");
        }

        // ── Core: Build sprite name cache ───────────────────────
        static Dictionary<string, Sprite> BuildSpriteCache()
        {
            var cache = new Dictionary<string, Sprite>(StringComparer.OrdinalIgnoreCase);

            // Find all Sprite assets in the project
            string[] guids = AssetDatabase.FindAssets("t:Sprite");
            foreach (string guid in guids)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                // Load all sprites from this asset (handles sprite sheets)
                var sprites = AssetDatabase.LoadAllAssetsAtPath(assetPath)
                    .OfType<Sprite>();

                foreach (var sprite in sprites)
                {
                    string spriteName = sprite.name;
                    string fileName = Path.GetFileNameWithoutExtension(assetPath);
                    string fileNameWithExt = Path.GetFileName(assetPath);

                    // Register by multiple keys for flexible matching
                    TryAdd(cache, spriteName, sprite);
                    TryAdd(cache, fileName, sprite);
                    TryAdd(cache, fileNameWithExt, sprite);
                    // Also register lowercase variants
                    TryAdd(cache, spriteName.ToLower(), sprite);
                    TryAdd(cache, fileName.ToLower(), sprite);
                }
            }

            // Also find Texture2D assets (for single-sprite textures)
            string[] texGuids = AssetDatabase.FindAssets("t:Texture2D");
            foreach (string guid in texGuids)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                // Skip internal Unity assets
                if (assetPath.StartsWith("Packages/") || !assetPath.StartsWith("Assets/"))
                    continue;

                var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
                if (sprite != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(assetPath);
                    string fileNameWithExt = Path.GetFileName(assetPath);
                    TryAdd(cache, fileName, sprite);
                    TryAdd(cache, fileNameWithExt, sprite);
                    TryAdd(cache, fileName.ToLower(), sprite);
                }
            }

            return cache;
        }

        static void TryAdd(Dictionary<string, Sprite> cache, string key, Sprite sprite)
        {
            if (!string.IsNullOrEmpty(key) && !cache.ContainsKey(key))
            {
                cache[key] = sprite;
            }
        }

        // ── Process a .sprite_names.json file ───────────────────
        static int ProcessNameMap(string jsonPath, Dictionary<string, Sprite> spriteCache)
        {
            int bound = 0;
            try
            {
                string json = File.ReadAllText(jsonPath);
                // Simple JSON parsing (avoid dependency on Newtonsoft)
                // The JSON format is: { "NodeName/Component/field": "filename.png", ... }
                var entries = ParseSimpleJson(json);

                // Find the associated prefab/scene file
                string basePath = jsonPath;
                // Remove .sprite_names.json → try .prefab, .unity
                string baseNoExt = jsonPath.Replace(".sprite_names.json", "");
                string prefabPath = baseNoExt + ".prefab";
                string scenePath = baseNoExt + ".unity";

                string targetPath = File.Exists(prefabPath) ? prefabPath : 
                                   File.Exists(scenePath) ? scenePath : null;

                if (targetPath == null)
                {
                    Debug.LogWarning($"[SpriteNameBinder] No matching prefab/scene for {jsonPath}");
                    return 0;
                }

                // Convert to relative path
                string assetsPath = Application.dataPath;
                string relativePath = "Assets" + targetPath.Substring(assetsPath.Length)
                    .Replace('\\', '/');

                // Load and process
                if (relativePath.EndsWith(".prefab"))
                {
                    bound = BindPrefabSprites(relativePath, spriteCache, entries);
                }
                else
                {
                    Debug.Log($"[SpriteNameBinder] Scene binding via name map: {relativePath}");
                    // For scenes, we'll handle via ScanAndBindOpenScenes
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"[SpriteNameBinder] Error processing {jsonPath}: {e.Message}");
            }
            return bound;
        }

        // ── Bind sprites in a prefab ────────────────────────────
        static int BindPrefabSprites(string prefabPath,
            Dictionary<string, Sprite> spriteCache,
            Dictionary<string, string> nameMap = null)
        {
            int bound = 0;
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
            if (prefab == null) return 0;

            // Get all Image components
            var images = prefab.GetComponentsInChildren<Image>(true);
            foreach (var img in images)
            {
                if (img.sprite != null) continue; // Already has a sprite

                string spriteName = FindSpriteNameForImage(img, nameMap);
                if (string.IsNullOrEmpty(spriteName)) continue;

                Sprite sprite = FindSprite(spriteName, spriteCache);
                if (sprite != null)
                {
                    img.sprite = sprite;
                    EditorUtility.SetDirty(img);
                    bound++;
                    Debug.Log($"[SpriteNameBinder] {GetPath(img.transform)}: " +
                        $"{spriteName} → {sprite.name}");
                }
                else
                {
                    Debug.LogWarning($"[SpriteNameBinder] {GetPath(img.transform)}: " +
                        $"No sprite found for '{spriteName}'");
                }
            }

            if (bound > 0)
            {
                EditorUtility.SetDirty(prefab);
            }

            return bound;
        }

        // ── Scan open scenes ────────────────────────────────────
        static int ScanAndBindOpenScenes(Dictionary<string, Sprite> spriteCache)
        {
            int bound = 0;

            // Find all Image components in the scene with missing sprites
            var allImages = UnityEngine.Object.FindObjectsOfType<Image>(true);
            foreach (var img in allImages)
            {
                if (img.sprite != null) continue;

                // Try to find sprite name from the YAML comment embedded during migration
                // The comment format is: # cocos_src: filename.png
                // Since we can't read YAML comments at runtime, use the name map approach
                string goName = img.gameObject.name;

                // Try matching by GameObject name (common pattern: node named after sprite)
                Sprite sprite = FindSprite(goName, spriteCache);
                if (sprite != null)
                {
                    img.sprite = sprite;
                    EditorUtility.SetDirty(img);
                    bound++;
                    Debug.Log($"[SpriteNameBinder] Scene: {GetPath(img.transform)} → {sprite.name}");
                }
            }

            return bound;
        }

        // ── Find sprite name for an Image component ─────────────
        static string FindSpriteNameForImage(Image img, Dictionary<string, string> nameMap)
        {
            if (nameMap == null) return img.gameObject.name;

            string path = GetPath(img.transform);

            // Try exact match: "NodeName/UnityEngine.UI.Image/spriteFrame"
            string key1 = $"{img.gameObject.name}/UnityEngine.UI.Image/spriteFrame";
            if (nameMap.TryGetValue(key1, out string name1)) return name1;

            // Try node name only
            foreach (var kvp in nameMap)
            {
                if (kvp.Key.StartsWith(img.gameObject.name + "/"))
                    return kvp.Value;
            }

            // Fallback: use GameObject name
            return img.gameObject.name;
        }

        // ── Find a Sprite by name ───────────────────────────────
        static Sprite FindSprite(string name, Dictionary<string, Sprite> cache)
        {
            if (string.IsNullOrEmpty(name)) return null;

            // Direct match
            if (cache.TryGetValue(name, out Sprite s1)) return s1;

            // Without extension
            string noExt = Path.GetFileNameWithoutExtension(name);
            if (!string.IsNullOrEmpty(noExt) && cache.TryGetValue(noExt, out Sprite s2))
                return s2;

            // Lowercase
            if (cache.TryGetValue(name.ToLower(), out Sprite s3)) return s3;
            if (!string.IsNullOrEmpty(noExt) && cache.TryGetValue(noExt.ToLower(), out Sprite s4))
                return s4;

            // AssetDatabase search as last resort
            string[] guids = AssetDatabase.FindAssets($"{noExt} t:Sprite");
            foreach (string guid in guids)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);
                string assetName = Path.GetFileNameWithoutExtension(assetPath);
                if (string.Equals(assetName, noExt, StringComparison.OrdinalIgnoreCase))
                {
                    var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
                    if (sprite != null)
                    {
                        cache[name] = sprite; // Cache for future lookups
                        return sprite;
                    }
                }
            }

            return null;
        }

        // ── Helpers ─────────────────────────────────────────────
        static string GetPath(Transform t)
        {
            var parts = new List<string>();
            while (t != null)
            {
                parts.Insert(0, t.name);
                t = t.parent;
            }
            return string.Join("/", parts);
        }

        /// <summary>
        /// Minimal JSON parser for flat string→string dictionaries.
        /// Handles the simple format output by _collect_sprite_names().
        /// Skips the __uuid_to_src__ entry (which is a nested dict).
        /// </summary>
        static Dictionary<string, string> ParseSimpleJson(string json)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            // Use Unity's built-in JSON utility? No, it doesn't support Dict directly.
            // Simple regex-based extraction for flat "key": "value" pairs.
            int i = 0;
            while (i < json.Length)
            {
                // Find next key
                int keyStart = json.IndexOf('"', i);
                if (keyStart < 0) break;
                int keyEnd = json.IndexOf('"', keyStart + 1);
                if (keyEnd < 0) break;
                string key = json.Substring(keyStart + 1, keyEnd - keyStart - 1);

                // Find colon
                int colon = json.IndexOf(':', keyEnd + 1);
                if (colon < 0) break;

                // Find value (skip whitespace)
                int valStart = colon + 1;
                while (valStart < json.Length && char.IsWhiteSpace(json[valStart]))
                    valStart++;

                if (valStart >= json.Length) break;

                if (json[valStart] == '"')
                {
                    // String value
                    int valEnd = json.IndexOf('"', valStart + 1);
                    if (valEnd < 0) break;
                    string value = json.Substring(valStart + 1, valEnd - valStart - 1);

                    if (!key.StartsWith("__")) // Skip internal keys
                    {
                        result[key] = value;
                    }
                    i = valEnd + 1;
                }
                else if (json[valStart] == '{')
                {
                    // Nested object — skip it
                    int depth = 1;
                    int j = valStart + 1;
                    while (j < json.Length && depth > 0)
                    {
                        if (json[j] == '{') depth++;
                        else if (json[j] == '}') depth--;
                        j++;
                    }
                    i = j;
                }
                else
                {
                    i = valStart + 1;
                }
            }
            return result;
        }
    }

    // ── Auto-bind on import ─────────────────────────────────────
    // Uncomment the class below to automatically bind sprites when
    // migrated prefabs/scenes are imported into Unity.
    //
    // public class SpriteNameBinderPostprocessor : AssetPostprocessor
    // {
    //     void OnPostprocessAllAssets(string[] imported, string[] deleted,
    //         string[] moved, string[] movedFrom)
    //     {
    //         bool hasNewAssets = imported.Any(p =>
    //             p.EndsWith(".prefab") || p.EndsWith(".unity"));
    //         if (hasNewAssets)
    //         {
    //             EditorApplication.delayCall += SpriteNameBinder.BindAllSprites;
    //         }
    //     }
    // }
}
