#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
apply_plan.py
Phase 2 bridge: reads a plan.json (output of convert_scene.py) and generates
a self-contained Unity Editor C# script that, when placed under an Editor/
folder, provides a menu item to rebuild the full hierarchy inside Unity.

This removes the need for any MCP bridge or proprietary agent integration —
the generated C# runs inside Unity's own scripting environment.

Supports plan format v1 and v2 (v2 adds active, z_order, widget anchors).

Usage:
  python apply_plan.py --plan plan.json --out Assets/_Ported/Editor/ApplyPlan_MyScene.cs
  python apply_plan.py --plan plan.json --out ApplyPlan.cs --menu-path "Tools/Cocos2Unity/Apply MyScene"
  python apply_plan.py --plan plan.json --out ApplyPlan.cs --ppu 100  (divide positions by PPU)

The generated script:
  - Creates all GameObjects with correct hierarchy (parent-child).
  - Sets Transform position/rotation/scale (with optional PPU conversion).
  - Sets active state matching the Cocos node.
  - Sorts siblings by z_order for correct draw order.
  - Adds mapped Unity components.
  - Sets serializable fields where possible.
  - Marks unmapped components as comments for manual resolution.
  - Provides a Unity menu item: Tools → Cocos2Unity → Apply Plan.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

HEADER_TEMPLATE = '''// Auto-generated by cocos-to-unity/apply_plan.py
// Menu: {menu_path}
// Source plan: {plan_source}
// Cocos format: {cocos_version}
//
// HOW TO USE:
//   1. Place this file under any Editor/ folder in your Unity project.
//   2. In Unity menu bar, click: {menu_path}
//   3. The hierarchy will be created under a root GameObject named "{root_name}".
//   4. Save the scene or right-click the root -> Create Prefab.
//   5. Delete this script after use (it is a one-time generator).

using UnityEngine;
using UnityEditor;

public static class {class_name}
{{
    [{menu_item_attr}]
    public static void Execute()
    {{
        Undo.IncrementCurrentGroup();
        int undoGroup = Undo.GetCurrentGroup();
        Undo.SetCurrentGroupName("Cocos2Unity Apply Plan");

        try
        {{
            BuildHierarchy();
            Debug.Log("[Cocos2Unity] Plan applied successfully. Root: {root_name}");
        }}
        catch (System.Exception ex)
        {{
            Debug.LogError("[Cocos2Unity] Failed: " + ex.Message + "\\n" + ex.StackTrace);
            Undo.RevertAllDownToGroup(undoGroup);
        }}
    }}

    private static void BuildHierarchy()
    {{
'''

FOOTER_TEMPLATE = '''
    }}
}}
'''


def sanitize_class_name(name: str) -> str:
    clean = "".join(c if c.isalnum() else "_" for c in name)
    if clean and clean[0].isdigit():
        clean = "_" + clean
    return f"ApplyPlan_{clean}"


def escape_cs(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def format_vector3(values: List[float]) -> str:
    if len(values) >= 3:
        return f"new Vector3({values[0]}f, {values[1]}f, {values[2]}f)"
    return "Vector3.zero"


def generate_cs(plan: Dict[str, Any], plan_source: str, menu_path: str, ppu: float) -> str:
    nodes: List[Dict[str, Any]] = plan.get("nodes", [])
    cocos_version = plan.get("cocos_version", "unknown")
    if not nodes:
        return "// Empty plan -- no nodes to create.\n"

    # Build index lookup
    index_map: Dict[int, int] = {}
    for i, n in enumerate(nodes):
        index_map[n["index"]] = i

    root_name = nodes[0].get("name", "CocosRoot") if nodes else "CocosRoot"
    class_name = sanitize_class_name(Path(plan_source).stem)
    menu_item_attr = f'MenuItem("{escape_cs(menu_path)}")'

    lines: List[str] = []
    lines.append(HEADER_TEMPLATE.format(
        menu_path=menu_path,
        plan_source=escape_cs(plan_source),
        root_name=escape_cs(root_name),
        class_name=class_name,
        menu_item_attr=menu_item_attr,
        cocos_version=cocos_version,
    ))

    # Declare all GameObjects
    lines.append(f"        // --- {len(nodes)} GameObjects ---")
    for i, node in enumerate(nodes):
        lines.append(f'        GameObject go_{i} = new GameObject("{escape_cs(node.get("name", f"Node_{i}"))}");')
        lines.append(f'        Undo.RegisterCreatedObjectUndo(go_{i}, "Create {escape_cs(node.get("name", ""))}");')

    lines.append("")
    lines.append("        // --- Hierarchy ---")

    # Set parent-child (sort children by z_order for correct draw order)
    children_by_parent: Dict[int, List[tuple]] = {}
    for i, node in enumerate(nodes):
        parent_idx = node.get("parent_index")
        if parent_idx is not None and parent_idx in index_map:
            pi = index_map[parent_idx]
            z = node.get("z_order", 0) or 0
            children_by_parent.setdefault(pi, []).append((z, i))

    # Sort children by z_order
    for pi in children_by_parent:
        children_by_parent[pi].sort(key=lambda x: x[0])

    # Set parents (in z_order)
    done_children = set()
    for pi, children in children_by_parent.items():
        for z, ci in children:
            lines.append(f"        go_{ci}.transform.SetParent(go_{pi}.transform, false);")
            done_children.add(ci)

    # Handle remaining parent relationships not captured above
    for i, node in enumerate(nodes):
        if i in done_children:
            continue
        parent_idx = node.get("parent_index")
        if parent_idx is not None and parent_idx in index_map:
            pi = index_map[parent_idx]
            lines.append(f"        go_{i}.transform.SetParent(go_{pi}.transform, false);")

    lines.append("")
    lines.append("        // --- Transforms ---")

    for i, node in enumerate(nodes):
        t = node.get("transform", {})
        pos = t.get("position", [0, 0, 0])
        euler = t.get("euler", [0, 0, 0])
        scale = t.get("scale", [1, 1, 1])

        # Detect UI status
        has_own_ui = any(
            (c.get("unity_component") or "").startswith("UnityEngine.UI.")
            or c.get("unity_component") in ("RectTransform", "RectTransform.anchors", "Canvas")
            for c in node.get("components", [])
        )
        # For simplicity in C# generator, we check if it has a RectTransform component
        has_ui = has_own_ui or any(c.get("unity_component") == "RectTransform" for c in node.get("components", []))

        # Apply PPU conversion if not already done in plan and NOT a UI node
        # (Unity UI usually stays in pixels relative to reference resolution)
        final_pos = list(pos)
        if not has_ui and ppu != 1.0:
            final_pos = [p / ppu for p in final_pos]

        lines.append(f"        go_{i}.transform.localPosition = {format_vector3(final_pos)};")

        if any(v != 0 for v in euler):
            lines.append(f"        go_{i}.transform.localEulerAngles = {format_vector3(euler)};")
        if scale != [1, 1, 1]:
            lines.append(f"        go_{i}.transform.localScale = {format_vector3(scale)};")

    # Set active state
    lines.append("")
    lines.append("        // --- Active State ---")
    for i, node in enumerate(nodes):
        active = node.get("active", True)
        if not active:
            lines.append(f"        go_{i}.SetActive(false);")

    lines.append("")
    lines.append("        // --- Components ---")

    for i, node in enumerate(nodes):
        for comp in node.get("components", []):
            unity_comp = comp.get("unity_component")
            cocos_type = comp.get("cocos_type", "unknown")

            if unity_comp is None:
                note = comp.get("note", "unmapped")
                lines.append(f"        // TODO(cocos2unity): [{cocos_type}] on go_{i} -- {note}")
                raw = comp.get("raw_fields", {})
                if raw:
                    for k, v in list(raw.items())[:5]:
                        lines.append(f"        //   {k} = {json.dumps(v, ensure_ascii=False)[:80]}")
                continue

            # Widget anchors → RectTransform setup
            if unity_comp == "RectTransform.anchors":
                anchors = comp.get("anchors", {})
                amin = anchors.get("anchorMin", [0.5, 0.5])
                amax = anchors.get("anchorMax", [0.5, 0.5])
                lines.append(f"        // Widget anchors for go_{i}")
                lines.append(f"        {{")
                lines.append(f"            var rt_{i} = go_{i}.GetComponent<RectTransform>();")
                lines.append(f"            if (rt_{i} == null) rt_{i} = go_{i}.AddComponent<RectTransform>();")
                lines.append(f"            rt_{i}.anchorMin = new Vector2({amin[0]}f, {amin[1]}f);")
                lines.append(f"            rt_{i}.anchorMax = new Vector2({amax[0]}f, {amax[1]}f);")
                offsets = anchors.get("offsets", {})
                if amin[0] == 0 and amax[0] == 1 and amin[1] == 0 and amax[1] == 1:
                    lines.append(f"            rt_{i}.offsetMin = new Vector2({offsets.get('left', 0)}f, {offsets.get('bottom', 0)}f);")
                    lines.append(f"            rt_{i}.offsetMax = new Vector2(-{offsets.get('right', 0)}f, -{offsets.get('top', 0)}f);")
                lines.append(f"        }}")
                continue

            # RectTransform size/pivot
            if unity_comp == "RectTransform":
                ct_size = comp.get("fields", {}).get("contentSize", {})
                if ct_size:
                    w = ct_size.get("width", 0)
                    h = ct_size.get("height", 0)
                    if w > 0 or h > 0:
                        lines.append(f"        // RectTransform sizeDelta for go_{i}")
                        lines.append(f"        {{")
                        lines.append(f"            var rt = go_{i}.GetComponent<RectTransform>();")
                        lines.append(f"            if (rt == null) rt = go_{i}.AddComponent<RectTransform>();")
                        lines.append(f"            rt.sizeDelta = new Vector2({w}f, {h}f);")
                        anchor = comp.get("fields", {}).get("anchorPoint", {})
                        if anchor:
                            ax = anchor.get("x", 0.5)
                            ay = anchor.get("y", 0.5)
                            if ax != 0.5 or ay != 0.5:
                                lines.append(f"            rt.pivot = new Vector2({ax}f, {ay}f);")
                        lines.append(f"        }}")
                continue

            # Custom user scripts
            if comp.get("note", "").startswith("Custom"):
                class_name = unity_comp
                if class_name and not class_name[0].isdigit():
                    lines.append(f"        // Custom component: {class_name} on go_{i}")
                    # Removed AddComponent as per user request to attach directly in YAML migration
                else:
                    lines.append(f"        // Custom component: {cocos_type} on go_{i} (skipped: invalid class name)")
                continue



            # Standard Components
            lines.append(f"        var c_{i}_{unity_comp.replace('.', '_')} = go_{i}.AddComponent<{unity_comp}>();")
            
            fields = comp.get("fields", {})
            if fields:
                # Handle color and alpha logic
                if unity_comp in ("UnityEngine.UI.Image", "SpriteRenderer", "UnityEngine.UI.Text"):
                    c_val = fields.get("color") or node.get("color")
                    if c_val:
                        r, g, b, a = c_val.get("r", 255), c_val.get("g", 255), c_val.get("b", 255), c_val.get("a", 255)
                        
                        # Empty sprite alpha 0 logic
                        sprite_field = "spriteFrame" if unity_comp == "UnityEngine.UI.Image" else "sprite"
                        if sprite_field in fields and fields[sprite_field] is None:
                            a = 0
                            lines.append(f"        // Auto-hiding node because {sprite_field} is empty")
                        
                        lines.append(f"        c_{i}_{unity_comp.replace('.', '_')}.color = new Color({r/255.0}f, {g/255.0}f, {b/255.0}f, {a/255.0}f);")

                # Text specific fields
                if unity_comp == "UnityEngine.UI.Text":
                    txt = fields.get("string", "")
                    if txt:
                        lines.append(f'        c_{i}_{unity_comp.replace(".", "_")}.text = "{escape_cs(str(txt))}";')
                    
                    fs = int(fields.get("fontSize") or 40)
                    lines.append(f'        c_{i}_{unity_comp.replace(".", "_")}.fontSize = {fs};')
                    
                    # Alignment
                    h = int(fields.get("horizontalAlign", 0))
                    v = int(fields.get("verticalAlign", 1))
                    # Row: TOP=0, CENTER=1, BOTTOM=2; Col: LEFT=0, CENTER=1, RIGHT=2
                    anchor = (v * 3) + h
                    lines.append(f'        c_{i}_{unity_comp.replace(".", "_")}.alignment = (TextAnchor){anchor};')
                    
                    lh = float(fields.get("lineHeight") or fs)
                    if lh > 0 and fs > 0:
                        lines.append(f'        c_{i}_{unity_comp.replace(".", "_")}.lineSpacing = {lh/fs}f;')

                # Outline specific fields
                if unity_comp == "UnityEngine.UI.Outline":
                    c_val = fields.get("color")
                    if c_val:
                        r, g, b, a = c_val.get("r", 0), c_val.get("g", 0), c_val.get("b", 0), c_val.get("a", 255)
                        lines.append(f"        c_{i}_{unity_comp.replace('.', '_')}.effectColor = new Color({r/255.0}f, {g/255.0}f, {b/255.0}f, {a/255.0}f);")
                    
                    w = float(fields.get("width", 1) or 1)
                    lines.append(f"        c_{i}_{unity_comp.replace('.', '_')}.effectDistance = new Vector2({w}f, {-w}f);")

                lines.append(f"        // Fields from Cocos ({cocos_type}):")


                for fname, fval in fields.items():
                    lines.append(f"        // TODO(cocos2unity): set {fname} = {json.dumps(fval, ensure_ascii=False)[:60]}")

    lines.append("")
    lines.append(f'        Selection.activeGameObject = go_0;')
    lines.append(FOOTER_TEMPLATE)

    return "\n".join(lines)


def _collect_referenced_assets(plan: Dict[str, Any], manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Collect all assets referenced by the plan from manifest entries."""
    referenced = []
    manifest_entries = manifest.get("entries", [])
    if not manifest_entries:
        return referenced

    referenced_uuids: set = set()
    for node in plan.get("nodes", []):
        for comp in node.get("components", []):
            fields = comp.get("fields", {})
            for fval in fields.values():
                if isinstance(fval, dict) and "__uuid__" in fval:
                    referenced_uuids.add(fval["__uuid__"])
                elif isinstance(fval, list):
                    for item in fval:
                        if isinstance(item, dict) and "__uuid__" in item:
                            referenced_uuids.add(item["__uuid__"])

    uuid_to_src = plan.get("uuid_to_src", {})
    for uuid in uuid_to_src:
        referenced_uuids.add(uuid)

    for entry in manifest_entries:
        if entry.get("cocos_uuid") in referenced_uuids:
            referenced.append(entry)
        src_name = entry.get("src", "")
        for uuid, name in uuid_to_src.items():
            if name and name.lower() in src_name.lower():
                referenced.append(entry)
                break

    seen = set()
    deduped = []
    for entry in referenced:
        dst = entry.get("dst", "")
        if dst and dst not in seen:
            seen.add(dst)
            deduped.append(entry)

    return deduped


def _copy_assets_to_unity(referenced: List[Dict[str, Any]], cocos_src_dir: Path, unity_dst_dir: Path) -> int:
    copied = 0
    for entry in referenced:
        src_rel = entry.get("src", "")
        dst_rel = entry.get("dst", "")
        if not src_rel or not dst_rel:
            continue
        src_path = cocos_src_dir / src_rel
        dst_path = unity_dst_dir / dst_rel
        if not src_path.exists(): continue
        dst_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dst_path)
        guid = entry.get("unity_guid", "")
        if guid:
            meta_path = dst_path.with_suffix(dst_path.suffix + ".meta")
            meta_path.write_text(f"fileFormatVersion: 2\nguid: {guid}\nTextureImporter: {{}}\n", encoding="utf-8")
        copied += 1
    return copied


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--plan", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--format", choices=["cs", "yaml"], default="cs")
    ap.add_argument("--menu-path", default="Tools/Cocos2Unity/Apply Plan")
    ap.add_argument("--ppu", type=float, default=1.0)
    ap.add_argument("--manifest")
    ap.add_argument("--src")
    ap.add_argument("--copy-assets", action="store_true")
    args = ap.parse_args()

    plan_path = Path(args.plan)
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    node_count = len(plan.get("nodes", []))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    if args.format == "yaml":
        sys.path.insert(0, str(Path(__file__).parent))
        from convert_prefab import plan_to_unity_yaml, prefab_meta, scene_meta, stable_guid
        is_scene = out.suffix.lower() == ".unity"
        manifest = json.loads(Path(args.manifest).read_text(encoding="utf-8")) if args.manifest else {}
        yaml_content = plan_to_unity_yaml(plan, is_scene=is_scene, manifest=manifest)
        out.write_text(yaml_content, encoding="utf-8")
        guid = stable_guid(f"cocos2unity:plan:{plan_path.name}")
        meta_fn = scene_meta if is_scene else prefab_meta
        out.with_suffix(out.suffix + ".meta").write_text(meta_fn(guid), encoding="utf-8")
        print(f"OK nodes={node_count} format=yaml out={out}")
    else:
        cs = generate_cs(plan, plan_path.name, args.menu_path, args.ppu)
        out.write_text(cs, encoding="utf-8")
        print(f"OK nodes={node_count} format=cs out={out}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
