import json
import argparse
import sys
from pathlib import Path
from typing import Dict, Any, List

HEADER = '''// Auto-generated by cocos-to-unity/convert_widget.py
// Applies cc.Widget anchor data to RectTransforms.
//
// HOW TO USE:
//   1. Place in an Editor/ folder.
//   2. Run the plan's main hierarchy builder first (ApplyPlan).
//   3. Then run: {menu_path}
//   4. This sets anchors/offsets on existing GameObjects by name.

using UnityEngine;
using UnityEditor;

public static class {class_name}
{{
    [{menu_attr}]
    public static void Execute()
    {{
        int applied = 0;
        int notFound = 0;
'''

FOOTER = '''
        Debug.Log($"[Cocos2Unity] Widget anchors applied: {applied}, not found: {notFound}");
    }
}
'''


def escape_cs(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate_widget_cs(plan: Dict[str, Any], menu_path: str) -> str:
    nodes = plan.get("nodes", [])
    widget_nodes: List[Dict[str, Any]] = []

    for node in nodes:
        node_name = node.get("name", "")
        for comp in node.get("components", []):
            # Existing Widget handling
            if comp.get("unity_component") == "RectTransform.anchors" and "anchors" in comp:
                widget_nodes.append({
                    "name": node_name,
                    "index": node.get("index", 0),
                    "anchors": comp["anchors"],
                })
            
            # New CanvasScaler handling
            if comp.get("unity_component") == "Canvas" and "fields" in comp:
                dr = comp["fields"].get("designResolution", {})
                w = dr.get("width", 0)
                h = dr.get("height", 0)
                if w > 0 and h > 0:
                    # Determine match value: 1 for portrait (w < h), 0 for landscape (w > h)
                    match_val = 1.0 if w < h else 0.0
                    widget_nodes.append({
                        "name": node_name,
                        "type": "CanvasScaler",
                        "match": match_val,
                        "resolution": (w, h)
                    })
            
            # New LayoutGroup handling
            if (comp.get("unity_component") or "").endswith("LayoutGroup"):
                fields = comp.get("fields", {})
                resize = int(fields.get("resizeMode", 0) or 0)
                widget_nodes.append({
                    "name": node_name,
                    "type": "LayoutGroup",
                    "comp_type": comp["unity_component"],
                    "force_expand": (0 if resize == 0 else 1)
                })

    if not widget_nodes:

        return "// No UI layout data found in plan.json\n"

    class_name = "ApplyWidgets"
    menu_attr = f'MenuItem("{escape_cs(menu_path)}")'

    lines = [HEADER.format(menu_path=menu_path, class_name=class_name, menu_attr=menu_attr)]

    for wn in widget_nodes:
        name = escape_cs(wn.get("name", ""))
        
        if wn.get("type") == "CanvasScaler":
            res = wn["resolution"]
            match = wn["match"]
            lines.append(f'        // Canvas Scaler for "{name}"')
            lines.append(f'        {{')
            lines.append(f'            var go = GameObject.Find("{name}");')
            lines.append(f'            if (go != null)')
            lines.append(f'            {{')
            lines.append(f'                var scaler = go.GetComponent<UnityEngine.UI.CanvasScaler>();')
            lines.append(f'                if (scaler == null) scaler = go.AddComponent<UnityEngine.UI.CanvasScaler>();')
            lines.append(f'                scaler.uiScaleMode = UnityEngine.UI.CanvasScaler.ScaleMode.ScaleWithScreenSize;')
            lines.append(f'                scaler.referenceResolution = new Vector2({res[0]}f, {res[1]}f);')
            lines.append(f'                scaler.screenMatchMode = UnityEngine.UI.CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;')
            lines.append(f'                scaler.matchWidthOrHeight = {match}f;')
            lines.append(f'                applied++;')
            lines.append(f'                EditorUtility.SetDirty(scaler);')
            lines.append(f'            }}')
            lines.append(f'        }}')
            lines.append('')
            continue

        if wn.get("type") == "LayoutGroup":
            comp_type = wn["comp_type"]
            fe = wn["force_expand"]
            lines.append(f'        // Layout Group for "{name}"')
            lines.append(f'        {{')
            lines.append(f'            var go = GameObject.Find("{name}");')
            lines.append(f'            if (go != null)')
            lines.append(f'            {{')
            lines.append(f'                var layout = go.GetComponent<UnityEngine.UI.{comp_type}>();')
            lines.append(f'                if (layout != null)')
            lines.append(f'                {{')
            lines.append(f'                    layout.childAlignment = TextAnchor.MiddleCenter;')
            if comp_type != "GridLayoutGroup":
                lines.append(f'                    layout.childForceExpandWidth = {fe == 1 and "true" or "false"};')
                lines.append(f'                    layout.childForceExpandHeight = {fe == 1 and "true" or "false"};')
            lines.append(f'                    applied++;')
            lines.append(f'                    EditorUtility.SetDirty(layout);')
            lines.append(f'                }}')
            lines.append(f'            }}')
            lines.append(f'        }}')
            lines.append('')
            continue

        anchors = wn["anchors"]


        amin = anchors.get("anchorMin", [0.5, 0.5])
        amax = anchors.get("anchorMax", [0.5, 0.5])
        offsets = anchors.get("offsets", {})
        flags = anchors.get("flags", {})

        lines.append(f'        // Node: "{name}" (index {wn["index"]})')
        lines.append(f'        {{')
        lines.append(f'            var go = GameObject.Find("{name}");')
        lines.append(f'            if (go != null)')
        lines.append(f'            {{')
        lines.append(f'                var rt = go.GetComponent<RectTransform>();')
        lines.append(f'                if (rt != null)')
        lines.append(f'                {{')
        lines.append(f'                    rt.anchorMin = new Vector2({amin[0]}f, {amin[1]}f);')
        lines.append(f'                    rt.anchorMax = new Vector2({amax[0]}f, {amax[1]}f);')

        # Apply offsets
        has_stretch_x = amin[0] == 0 and amax[0] == 1
        has_stretch_y = amin[1] == 0 and amax[1] == 1

        if has_stretch_x and has_stretch_y:
            left = offsets.get("left", 0)
            right = offsets.get("right", 0)
            top = offsets.get("top", 0)
            bottom = offsets.get("bottom", 0)
            lines.append(f'                    rt.offsetMin = new Vector2({left}f, {bottom}f);')
            lines.append(f'                    rt.offsetMax = new Vector2(-{right}f, -{top}f);')
        elif has_stretch_x:
            left = offsets.get("left", 0)
            right = offsets.get("right", 0)
            lines.append(f'                    rt.offsetMin = new Vector2({left}f, rt.offsetMin.y);')
            lines.append(f'                    rt.offsetMax = new Vector2(-{right}f, rt.offsetMax.y);')
        elif has_stretch_y:
            top = offsets.get("top", 0)
            bottom = offsets.get("bottom", 0)
            lines.append(f'                    rt.offsetMin = new Vector2(rt.offsetMin.x, {bottom}f);')
            lines.append(f'                    rt.offsetMax = new Vector2(rt.offsetMax.x, -{top}f);')
        else:
            # Point anchor — use anchoredPosition
            hc = offsets.get("horizontalCenter", 0)
            vc = offsets.get("verticalCenter", 0)
            if hc or vc:
                lines.append(f'                    rt.anchoredPosition = new Vector2({hc}f, {vc}f);')

        lines.append(f'                    applied++;')
        lines.append(f'                    EditorUtility.SetDirty(rt);')
        lines.append(f'                }}')
        lines.append(f'            }}')
        lines.append(f'            else {{ notFound++; }}')
        lines.append(f'        }}')
        lines.append('')

    lines.append(FOOTER)
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Convert cc.Widget data to Unity RectTransform anchor script")
    ap.add_argument("--plan", required=True, help="Input plan.json")
    ap.add_argument("--out", required=True, help="Output .cs file")
    ap.add_argument("--menu-path", default="Tools/Cocos2Unity/Apply Widgets",
                    help="Unity menu path")
    args = ap.parse_args()

    plan = json.loads(Path(args.plan).read_text(encoding="utf-8"))
    cs = generate_widget_cs(plan, args.menu_path)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(cs, encoding="utf-8")

    # Count widgets
    count = sum(1 for n in plan.get("nodes", [])
                for c in n.get("components", [])
                if c.get("unity_component") == "RectTransform.anchors")
    print(f"OK widgets={count} out={out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
